POST http://localhost:8080/api/members/register
Content-Type: application/json

{
  "email": "soon950207@naver.com",
  "password": "123123a"
}

###
POST localhost:8080/login
Content-Type: application/json

{
  "email": "soon950207@naver.com",
  "password": "123123a"
}